name: Run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1.14.2
        with:
          perl-version: '5.34'
      - name: Install perl modules
        run: cpanm --installdeps .
      - name: Run tests
        run: prove -lrv t
