name: Run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1.14.2
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure
      - name: Run tests
        run: yath - t
